# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deleterious < Formula
  desc "Deleterious helps find orphaned resources from AWS CloudFormation DeletionPolicy: Retain"
  homepage "https://github.com/kindlyops/deleterious"
  version "0.1.41"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kindlyops/deleterious/releases/download/v0.1.41/deleterious_0.1.41_darwin_amd64.tar.gz"
      sha256 "50df7149d5d7e1a72317d29a24d83c1c2519ea34fb8e3f8db7664f7aee8c3afb"

      def install
        bin.install "deleterious"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kindlyops/deleterious/releases/download/v0.1.41/deleterious_0.1.41_darwin_arm64.tar.gz"
      sha256 "50df7149d5d7e1a72317d29a24d83c1c2519ea34fb8e3f8db7664f7aee8c3afb"

      def install
        bin.install "deleterious"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindlyops/deleterious/releases/download/v0.1.41/deleterious_0.1.41_linux_arm64.tar.gz"
      sha256 "5b1ac1cc999c02a9e2ca049cfd93841c821dc0d90fe066e455a84a79ba82579d"

      def install
        bin.install "deleterious"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kindlyops/deleterious/releases/download/v0.1.41/deleterious_0.1.41_linux_amd64.tar.gz"
      sha256 "69a4adc4750869f2f45ea99900fbcb74e1eba57ed42c0e252d24fb41f445f7e0"

      def install
        bin.install "deleterious"
      end
    end
  end

  def caveats; <<~EOS
    Brought to you by

    _  ___           _ _        ___
    | |/ (_)_ __   __| | |_   _ / _ \\ _ __  ___
    | ' /| | '_ \\ / _| | | | | | | | | '_ \\/ __|
    | . \\| | | | | (_| | | |_| | |_| | |_) \__ \\
    |_|\\_\\_|_| |_|\\__,_|_|\\__, |\\___/| .__/|___/
                          |___/      |_|
    use at your own risk.
  EOS
  end

  test do
    system "#{bin}/deleterious --version"
  end
end
