# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deleterious < Formula
  desc "Deleterious helps find orphaned resources from AWS CloudFormation DeletionPolicy: Retain"
  homepage "https://github.com/kindlyops/deleterious"
  version "0.1.46"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kindlyops/deleterious/releases/download/v0.1.46/deleterious_0.1.46_darwin_arm64.tar.gz"
      sha256 "59163bac69aa102a7ca491f8ffb29bb10b964fa9404476d17c599a1579c3939f"

      def install
        bin.install "deleterious"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kindlyops/deleterious/releases/download/v0.1.46/deleterious_0.1.46_darwin_amd64.tar.gz"
      sha256 "59163bac69aa102a7ca491f8ffb29bb10b964fa9404476d17c599a1579c3939f"

      def install
        bin.install "deleterious"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindlyops/deleterious/releases/download/v0.1.46/deleterious_0.1.46_linux_arm64.tar.gz"
      sha256 "7a8641bf940c7b4f7f3fd701095bc534b6f9f60a0f5def7a982b0e6ee824023d"

      def install
        bin.install "deleterious"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kindlyops/deleterious/releases/download/v0.1.46/deleterious_0.1.46_linux_amd64.tar.gz"
      sha256 "2d502c64184b809322189f4725d76108f265855bb871cdd6d7e76bfabe75d95b"

      def install
        bin.install "deleterious"
      end
    end
  end

  def caveats; <<~EOS
    Brought to you by

    _  ___           _ _        ___
    | |/ (_)_ __   __| | |_   _ / _ \\ _ __  ___
    | ' /| | '_ \\ / _| | | | | | | | | '_ \\/ __|
    | . \\| | | | | (_| | | |_| | |_| | |_) \__ \\
    |_|\\_\\_|_| |_|\\__,_|_|\\__, |\\___/| .__/|___/
                          |___/      |_|
    use at your own risk.
  EOS
  end

  test do
    system "#{bin}/deleterious --version"
  end
end
