# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Streamer < Formula
  desc "🚣 streamer is utilities for working with kinesis"
  homepage "https://github.com/kindlyops/streamer"
  version "0.1.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kindlyops/streamer/releases/download/v0.1.1/streamer_0.1.1_darwin_amd64.tar.gz"
    sha256 "b5a1da1549e23f06ed77f3edd9612c7ba97ec727ed127c6305bebdc6c3e88aea"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kindlyops/streamer/releases/download/v0.1.1/streamer_0.1.1_linux_amd64.tar.gz"
    sha256 "cf721dc5d1a2576a47e000ddd182540856439a7920a5096fdde0c32f92ebf469"
  end

  def install
    bin.install "streamer"
  end

  def caveats; <<~EOS
    Brought to you by

    _  ___           _ _        ___
    | |/ (_)_ __   __| | |_   _ / _ \\ _ __  ___
    | ' /| | '_ \\ / _| | | | | | | | | '_ \\/ __|
    | . \\| | | | | (_| | | |_| | |_| | |_) \__ \\
    |_|\\_\\_|_| |_|\\__,_|_|\\__, |\\___/| .__/|___/
                          |___/      |_|
    use at your own risk.
  EOS
  end

  test do
    system "#{bin}/streamer --version"
  end
end
