# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Streamer < Formula
  desc "🚣 streamer is utilities for working with kinesis"
  homepage "https://github.com/kindlyops/streamer"
  version "0.1.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kindlyops/streamer/releases/download/v0.1.2/streamer_0.1.2_darwin_amd64.tar.gz"
    sha256 "077eade474789e1b2706a704668ab5bc318230d84066e74934689d046a96035c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kindlyops/streamer/releases/download/v0.1.2/streamer_0.1.2_linux_amd64.tar.gz"
    sha256 "56115d939cda906e6aeeb83065bd41753491587ef33cba1358a93a02957104ea"
  end

  def install
    bin.install "streamer"
  end

  def caveats; <<~EOS
    Brought to you by

    _  ___           _ _        ___
    | |/ (_)_ __   __| | |_   _ / _ \\ _ __  ___
    | ' /| | '_ \\ / _| | | | | | | | | '_ \\/ __|
    | . \\| | | | | (_| | | |_| | |_| | |_) \__ \\
    |_|\\_\\_|_| |_|\\__,_|_|\\__, |\\___/| .__/|___/
                          |___/      |_|
    use at your own risk.
  EOS
  end

  test do
    system "#{bin}/streamer --version"
  end
end
