# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terp < Formula
  desc "🙈 terp is an experimental eBPF diagnostic interpreter"
  homepage "https://github.com/kindlyops/terp"
  version "0.0.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kindlyops/terp/releases/download/v0.0.2/terp_0.0.2_darwin_amd64.tar.gz"
    sha256 "ba34568c768e100e5eb1c11de628bdc518894274965a589f4c70e28fa6330a91"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kindlyops/terp/releases/download/v0.0.2/terp_0.0.2_linux_amd64.tar.gz"
    sha256 "1d134f400a87afb8620ba7c8ce9f2e015b7b101c5318383897f5f78fabc4a72f"
  end

  def install
    bin.install "terp"
  end

  def caveats; <<~EOS
    Brought to you by

    _  ___           _ _        ___
    | |/ (_)_ __   __| | |_   _ / _ \\ _ __  ___
    | ' /| | '_ \\ / _| | | | | | | | | '_ \\/ __|
    | . \\| | | | | (_| | | |_| | |_| | |_) \__ \\
    |_|\\_\\_|_| |_|\\__,_|_|\\__, |\\___/| .__/|___/
                          |___/      |_|
    use at your own risk.
  EOS
  end

  test do
    system "#{bin}/terp --version"
  end
end
