# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vbs < Formula
  desc "vbs helps work with video broadcast files and streams."
  homepage "https://github.com/kindlyops/vbs"
  version "0.1.12"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kindlyops/vbs/releases/download/v0.1.12/vbs_0.1.12_darwin_amd64.tar.gz"
      sha256 "62e1086e740b724aafb318bb9a28b25a88f133bda6b5bc6aed94e75e8fcc6225"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kindlyops/vbs/releases/download/v0.1.12/vbs_0.1.12_linux_amd64.tar.gz"
      sha256 "205ec6004361e723029aaeeb9f28e6d1c2374858a495998fe3e89ef59db3a3c5"
    end
  end

  def install
    bin.install "vbs"
  end

  def caveats; <<~EOS
    Brought to you by

    _  ___           _ _        ___
    | |/ (_)_ __   __| | |_   _ / _ \\ _ __  ___
    | ' /| | '_ \\ / _| | | | | | | | | '_ \\/ __|
    | . \\| | | | | (_| | | |_| | |_| | |_) \__ \\
    |_|\\_\\_|_| |_|\\__,_|_|\\__, |\\___/| .__/|___/
                          |___/      |_|
    use at your own risk.
  EOS
  end

  test do
    system "#{bin}/vbs --version"
  end
end
