# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vbs < Formula
  desc "vbs helps work with video broadcast files and streams."
  homepage "https://github.com/kindlyops/vbs"
  version "0.2.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kindlyops/vbs/releases/download/v0.2.9/vbs_0.2.9_darwin_amd64.tar.gz"
      sha256 "bab0aa3cb8c7c0253bd555effcea0014fbb7881906413993cc9ad3897f2c658c"

      def install
        bin.install "vbs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kindlyops/vbs/releases/download/v0.2.9/vbs_0.2.9_darwin_arm64.tar.gz"
      sha256 "84c67b1efb734c513347ad0f5a4ffe2cbed7f28e682b0cf4cc9bc92f92de6518"

      def install
        bin.install "vbs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kindlyops/vbs/releases/download/v0.2.9/vbs_0.2.9_linux_amd64.tar.gz"
      sha256 "0f6ecbd25e10c4947653edd385c3445e61fb34d8290b1357e6e2eadf045004dd"

      def install
        bin.install "vbs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindlyops/vbs/releases/download/v0.2.9/vbs_0.2.9_linux_arm64.tar.gz"
      sha256 "d57851245dec59caab385385c881e7f6dff9787f2d6d442e6b84e872d6529b5b"

      def install
        bin.install "vbs"
      end
    end
  end

  def caveats
    <<~EOS
      Brought to you by

      _  ___           _ _        ___
      | |/ (_)_ __   __| | |_   _ / _ \\ _ __  ___
      | ' /| | '_ \\ / _| | | | | | | | | '_ \\/ __|
      | . \\| | | | | (_| | | |_| | |_| | |_) \__ \\
      |_|\\_\\_|_| |_|\\__,_|_|\\__, |\\___/| .__/|___/
                            |___/      |_|
      use at your own risk.
    EOS
  end

  test do
    system "#{bin}/vbs --version"
  end
end
