# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vbs < Formula
  desc "vbs helps work with video broadcast files and streams."
  homepage "https://github.com/kindlyops/vbs"
  version "0.2.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kindlyops/vbs/releases/download/v0.2.10/vbs_0.2.10_darwin_amd64.tar.gz"
      sha256 "0f2c7f71a140380a94757772f319a2e9e9bdfa8a5e270148ce006b9964925009"

      def install
        bin.install "vbs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kindlyops/vbs/releases/download/v0.2.10/vbs_0.2.10_darwin_arm64.tar.gz"
      sha256 "ea18ed8e9b9ae9c7cab2c93dddbfdc08bd594320dc6b74cdb0485fa9a1a8711f"

      def install
        bin.install "vbs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kindlyops/vbs/releases/download/v0.2.10/vbs_0.2.10_linux_amd64.tar.gz"
      sha256 "6c942c0c7f6a4c6e030228b41ddbd92cc85f1fa7aafff2e2eaa157509dcb150d"

      def install
        bin.install "vbs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindlyops/vbs/releases/download/v0.2.10/vbs_0.2.10_linux_arm64.tar.gz"
      sha256 "77d28e814b7bc1104528baefcf4d523bf8bd7fb76ed22872d8c3cb6916e4f22e"

      def install
        bin.install "vbs"
      end
    end
  end

  def caveats
    <<~EOS
      Brought to you by

      _  ___           _ _        ___
      | |/ (_)_ __   __| | |_   _ / _ \\ _ __  ___
      | ' /| | '_ \\ / _| | | | | | | | | '_ \\/ __|
      | . \\| | | | | (_| | | |_| | |_| | |_) \__ \\
      |_|\\_\\_|_| |_|\\__,_|_|\\__, |\\___/| .__/|___/
                            |___/      |_|
      use at your own risk.
    EOS
  end

  test do
    system "#{bin}/vbs --version"
  end
end
