# This file was generated by GoReleaser. DO NOT EDIT.
cask "vbs" do
  version "0.2.15"

  on_macos do
    on_intel do
      sha256 "9169e276754e12821226b7508dd590599ef2d20acb02a9cbdf3429226d4a833f"
      url "https://github.com/kindlyops/vbs/releases/download/v#{version}/vbs_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0d66f0de4270771f0cd06d0cd01fe03013d627692294c49631f5cb7d13d0d66"
      url "https://github.com/kindlyops/vbs/releases/download/v#{version}/vbs_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1784e55168d1202ccedd71ecd267b56bf0427be5b4fc41b13f1efff2154f3e36"
      url "https://github.com/kindlyops/vbs/releases/download/v#{version}/vbs_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3cc1ec41cc166e7e8ab1d0f9a1b313be09a0f93967d14fd3d59d88eaa823c514"
      url "https://github.com/kindlyops/vbs/releases/download/v#{version}/vbs_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vbs"
  desc "vbs helps work with video broadcast files and streams."
  homepage "https://github.com/kindlyops/vbs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vbs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vbs"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Brought to you by

    _  ___           _ _        ___
    | |/ (_)_ __   __| | |_   _ / _ \\ _ __  ___
    | ' /| | '_ \\ / _| | | | | | | | | '_ \\/ __|
    | . \\| | | | | (_| | | |_| | |_| | |_) \__ \\
    |_|\\_\\_|_| |_|\\__,_|_|\\__, |\\___/| .__/|___/
                          |___/      |_|
    use at your own risk.
  EOS
end
